### PR TITLE
Merge updates to dev branch which adds support for multiple controllers

### PR DESCRIPTION
**Pull request by SkeLLLa**
In dev branch there's an initial implementation of multiple controllers support. Currently if in API non-supported controller goes first, then it's impossible to add second one which is supported.

Or you can merge dev to main.

### CODE REVIEW

**Comment by michal-krasowski-red** [comment]
I need to get better on observing the repo, sorry

**Comment by MichalKrasowski** [comment]
Resolve conflicts first please.

**Comment by jontofront** [comment]
@SkeLLLa

**Comment by wkryzel** [comment]
Czy integracja działa z ST-5305?

**Comment by MichalKrasowski** [comment]
This PR stalled. Reopen with resolved conflicts

**Pull request closed without merging**
