### PR TITLE
Added multi module support and humidity

### PR DESCRIPTION
**Pull request by andrew-dddd**
Added showing humidity in the tile
image

Multiple module support - type in your creds and HA will configure separate config entries for each module:
image

### CODE REVIEW

**Comment by andrew-dddd** [comment]
@MichalKrasowski if you would have some spare time please review this pr. Thanks.

**Comment by jakubczaplicki** [comment]
@andrew-dddd  great work! I've been looking into this code few weeks ago and I can confirm that I'd take similar approach.

btw. How do you test this code ? How do one test such HA integrations ? Do you run those on your own "production " setup in the office/at home ?

**Comment by jakubczaplicki** [comment]
Also, you may want to consider bumping version  to `"1.0.1"` in manifest.json . Unless that's reserved for releases only.

**Comment by andrew-dddd** [comment]
@jakubczaplicki 
> How do you test this code ? How do one test such HA integrations ? Do you run those on your own "production " setup in the office/at home ?

I have set up repo on my soon-to-be production instance of home assistant, and then I just wrote code on my PC, pushed it to the repo, pulled on HA and tested it and so on. In order to debug I used `Turn on debugging` feature from the custom integration: 
image
Lots of hustle, but for two-three days of code worked out. 

> Also, you may want to consider bumping version to "1.0.1" in manifest.json . Unless that's reserved for releases only.

I am leaving such decisions for the repo owner

**Review by MichalKrasowski — APPROVED** [review]
Looks good, thank you for the contribution :smile: 
Sorry for long reply intervals, not much time lately for opensource :sweat_smile:

**Comment by jakubczaplicki** [comment]
@MichalKrasowski  , @andrew-dddd  Great work guys! Let's keep the ball rolling and merge it :) 
@MichalKrasowski  would you have time to release the new version once this PR is merged ?

**Pull request merged**
